In [113]:
import pandas as pd
import numpy as np
df= pd.read_csv("movie_dataset.csv")
df.head()
df.isna().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [114]:
df['keywords'].replace(np.nan,'', inplace=True)
df['director'].replace(np.nan,'', inplace=True)
#,'genres','cast','director'
df['cast'].replace(np.nan,'', inplace=True)
df['genres'].replace(np.nan,'', inplace=True)
df.isna().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [115]:
features=['keywords','cast','genres','director']
def combine_features(row):
        return row['keywords']+''+row['cast']+''+row['genres']+''+row['director']
#passing  a method to a df
df["combine_features"]=df.apply(combine_features, axis=1)
df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ...  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   
3  Following the death of District Attorney Harve...  112.312950  ...   
4  John Carter is a war-weary, former military ca...   43.926995  ...   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average vote_count  \
0                                    Avatar           7.2      11800   
1  Pirates of the Caribbean: At World's End           6.9       4500   
2                                   Spectre           6.3       4466   
3                     The Dark Knight Rises           7.6       9106   
4                               John Carter           6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  \
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron   
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski   
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes   
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan   
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton   

                                    combine_features  
0  culture clash future space war space colony so...  
1  ocean drug abuse exotic island east indi

In [116]:
from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer()
x=vec.fit_transform(df["combine_features"])
print(x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [117]:
from sklearn.metrics.pairwise import cosine_similarity
sim_scr=cosine_similarity(x)
print (sim_scr)

[[1.         0.03928371 0.04564355 ... 0.         0.         0.        ]
 [0.03928371 1.         0.         ... 0.0410305  0.         0.        ]
 [0.04564355 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.0410305  0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [119]:
movie=input("Enter movie: ")

Enter movie: Spectre


In [123]:
sim_scr=-np.sort(-sim_scr)
#print(sim_scr)
def get_index(t):
    return df[df.title==t]["index"].values[0]
def get_title(i):
    return df[df.index==i]['title'].values[0]
movie_index=get_index(movie)
sim_movies=list(enumerate(sim_scr[movie_index]))
print(sim_movies)

[(0, 1.0000000000000002), (1, 0.4103913408340616), (2, 0.23836564731139806), (3, 0.23094010767585027), (4, 0.22821773229381925), (5, 0.22821773229381923), (6, 0.21128856368212912), (7, 0.2051956704170308), (8, 0.2051956704170308), (9, 0.19999999999999998), (10, 0.19999999999999998), (11, 0.19999999999999998), (12, 0.19999999999999998), (13, 0.19999999999999998), (14, 0.19518001458970663), (15, 0.19518001458970663), (16, 0.19518001458970663), (17, 0.19518001458970663), (18, 0.19518001458970663), (19, 0.1917412472118426), (20, 0.19069251784911845), (21, 0.19069251784911845), (22, 0.19069251784911845), (23, 0.19069251784911845), (24, 0.19069251784911845), (25, 0.18650096164806276), (26, 0.18650096164806276), (27, 0.18650096164806276), (28, 0.18650096164806276), (29, 0.18650096164806276), (30, 0.18257418583505539), (31, 0.18257418583505539), (32, 0.17888543819998318), (33, 0.17888543819998318), (34, 0.17888543819998318), (35, 0.17541160386140586), (36, 0.1732050807568877), (37, 0.172132593

In [108]:
sorted_sim_movies=sorted(sim_movies,key=lambda x:x[1], reverse=True)

In [109]:
count=0
for movie in sorted_sim_movies: 
    if count<15:
            print(get_title(movie[0]))
            count=count+1

Avatar
Pirates of the Caribbean: At World's End
Spectre
The Dark Knight Rises
John Carter
Spider-Man 3
Tangled
Avengers: Age of Ultron
Harry Potter and the Half-Blood Prince
Batman v Superman: Dawn of Justice
Superman Returns
Quantum of Solace
Pirates of the Caribbean: Dead Man's Chest
The Lone Ranger
Man of Steel
